CREATE TABLE Task (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT NOT NULL,
    assigner_id INT NOT NULL,
    assignee_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    planned_start_date DATE,
    deadline DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    status_comment VARCHAR(500)

    FOREIGN KEY (project_id) REFERENCES Project(id) ON DELETE CASCADE,
    FOREIGN KEY (assigner_id) REFERENCES Person(id) ON DELETE CASCADE,
    FOREIGN KEY (assignee_id) REFERENCES Person(id) ON DELETE CASCADE
);