-- Таблица разделов
CREATE TABLE IF NOT EXISTS discipline (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_name VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    visible BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0
);

-- Начальное заполнение (13 разделов)
INSERT INTO discipline (short_name, full_name, sort_order) VALUES
('АР', 'Архитектурные решения', 1),
('АС', 'Архитектурно-строительные решения', 2),
('КР', 'Конструктивные решения', 3),
('КЖ', 'Конструкции железобетонные', 4),
('КЖИ', 'Конструкции железобетонные изделия', 5),
('КМ', 'Конструкции металлические', 6),
('КД', 'Конструкции деревянные', 7),
('ИОС', 'Инженерное оборудование и сети', 8),
('ВК', 'Водоснабжение и канализация', 9),
('ОВиК', 'Отопление, вентиляция и кондиционирование', 10),
('ЭОМ', 'Электрооборудование и электроосвещение', 11),
('ЭС', 'Электроснабжение', 12),
('СС', 'Слаботочные сети и системы', 13);

-- Добавление колонки discipline_id в задачу
ALTER TABLE task ADD COLUMN discipline_id INT;
ALTER TABLE task ADD FOREIGN KEY (discipline_id) REFERENCES discipline(id) ON DELETE SET NULL;